import { QueryInterface, DataTypes, Op } from "sequelize"
import { v4 } from "uuid"
import bcrypt from "bcrypt"
import generator from "generate-password"
// local imports
import * as config from "../../../config"

module.exports = {
    up: async (query: QueryInterface) => {
        try {
            await query.bulkInsert("role_master", [
                {
                    id: 1,
                    name: "System Administrator",
                    description: "Super user generated by the system",
                    uuid: v4(),
                    isSystemGenerated: true,
                    isActive: true,
                },
                {
                    id: 2,
                    name: "User",
                    description: "Normal user generated by the system",
                    uuid: v4(),
                    isSystemGenerated: true,
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
            ])
            await query.bulkInsert("permission_master", [
                {
                    id: 1,
                    name: "user_login",
                    description: null,
                    displayName: "User - Login",
                    group: "Public",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
            ])
            await query.bulkInsert("emp_basic_detail", [
                {
                    id: 1,
                    empCode: "SYSADM",
                    firstName: config.SysAdm.name,
                    mobile: config.SysAdm.contactNo,
                    email: config.SysAdm.email,
                    birthDate: new Date(),
                    uuid: v4(),
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
            ])
            const generatedPassword = generator.generate({
                length: 20,
                lowercase: true,
                uppercase: true,
                numbers: true,
                strict: true,
                symbols: true,
            })
            console.log(`Please keep password safe: ` + generatedPassword)
            await query.bulkInsert("user_login", [
                {
                    id: 1,
                    empId: 1,
                    roleId: 1,
                    contactNo: config.SysAdm.contactNo,
                    email: config.SysAdm.email,
                    passwordHash: bcrypt.hashSync(generatedPassword, 12),
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
            ])
        } catch (error) {
            console.log(error)
        }
    },
    down: async (query: QueryInterface) => {
        await query.bulkDelete("user_login", {
            id: {
                [Op.eq]: 1,
            },
        })
        await query.bulkDelete("role_master", {
            id: {
                [Op.in]: [1, 2],
            },
        })
        await query.bulkDelete("permission_master", {
            id: {
                [Op.eq]: 1,
            },
        })
    },
}
