import { QueryInterface, DataTypes, Op } from "sequelize"
import { v4 } from "uuid"
import bcrypt from "bcrypt"
import generator from "generate-password"
// local imports
import * as config from "../../../config"

module.exports = {
    up: async (query: QueryInterface) => {
        try {
            await query.bulkInsert("permission_master", [
                {
                    id: 2,
                    name: "user_self_upload_document",
                    description: null,
                    displayName: "Upload document",
                    group: "User - Self",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
                {
                    id: 3,
                    name: "user_self_read_uploaded_documents",
                    description: null,
                    displayName: "Read all uploaded documents",
                    group: "User - Self",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
                {
                    id: 4,
                    name: "user_self_download_document",
                    description: null,
                    displayName: "Download document",
                    group: "User - Self",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
                {
                    id: 5,
                    name: "user_self_read_esic_no",
                    description: null,
                    displayName: "Read ESIC No",
                    group: "User - Self",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
                {
                    id: 6,
                    name: "user_self_read_uan_no",
                    description: null,
                    displayName: "Read UAN No",
                    group: "User - Self",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
                {
                    id: 7,
                    name: "user_self_read_pf_no",
                    description: null,
                    displayName: "Read PF No",
                    group: "User - Self",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
                {
                    id: 8,
                    name: "user_self_read_aadhar_no",
                    description: null,
                    displayName: "Read Aadhar No",
                    group: "User - Self",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
                {
                    id: 9,
                    name: "user_self_read_pan_no",
                    description: null,
                    displayName: "Read Pan No",
                    group: "User - Self",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
                {
                    id: 10,
                    name: "user_self_read_pf_amount",
                    description: null,
                    displayName: "Read PF Amount",
                    group: "User - Self",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
                {
                    id: 11,
                    name: "user_self_read_esic_amount",
                    description: null,
                    displayName: "Read ESIC Amount",
                    group: "User - Self",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
                {
                    id: 12,
                    name: "employee_bulk_create",
                    description: null,
                    displayName: "Bulk create",
                    group: "Employee",
                    isActive: true,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                },
            ])
            await query.bulkInsert("role_permission", [
                {
                    id: 1,
                    roleId: 1,
                    permissionId: 1,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 2,
                    roleId: 1,
                    permissionId: 2,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 3,
                    roleId: 1,
                    permissionId: 3,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 4,
                    roleId: 1,
                    permissionId: 4,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 5,
                    roleId: 1,
                    permissionId: 5,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 6,
                    roleId: 1,
                    permissionId: 6,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 7,
                    roleId: 1,
                    permissionId: 7,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 8,
                    roleId: 1,
                    permissionId: 8,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 9,
                    roleId: 1,
                    permissionId: 9,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 10,
                    roleId: 1,
                    permissionId: 10,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 11,
                    roleId: 1,
                    permissionId: 11,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 12,
                    roleId: 1,
                    permissionId: 12,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 13,
                    roleId: 2,
                    permissionId: 1,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 14,
                    roleId: 2,
                    permissionId: 2,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 15,
                    roleId: 2,
                    permissionId: 3,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 16,
                    roleId: 2,
                    permissionId: 4,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 17,
                    roleId: 2,
                    permissionId: 5,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 18,
                    roleId: 2,
                    permissionId: 6,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 19,
                    roleId: 2,
                    permissionId: 7,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 20,
                    roleId: 2,
                    permissionId: 8,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 21,
                    roleId: 2,
                    permissionId: 9,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 22,
                    roleId: 2,
                    permissionId: 10,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
                {
                    id: 23,
                    roleId: 2,
                    permissionId: 11,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                    createdBy: 1,
                    modifiedBy: 1,
                },
            ])
        } catch (error) {
            console.log(error)
        }
    },
    down: async (query: QueryInterface) => {
        await query.bulkDelete("role_permission", {
            id: {
                [Op.between]: [1, 23],
            },
        })
        await query.bulkDelete("permission_master", {
            id: {
                [Op.between]: [2, 12],
            },
        })
    },
}
