// insert default permissions
import { QueryInterface, Op } from "sequelize"

module.exports = {
    up: async (query: QueryInterface) => {
        const t = await query.sequelize.transaction()
        try {
            await query.startTransaction(t)
            // Create system permissions in permissin master table
            await query.bulkInsert(
                "permission_master",
                [
                    {
                        id: 1,
                        name: "user_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "User",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 2,
                        name: "user_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "User",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 3,
                        name: "user_create",
                        description: null,
                        displayName: "Create",
                        group: "User",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 4,
                        name: "user_update",
                        description: null,
                        displayName: "Update",
                        group: "User",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 5,
                        name: "user_self_read",
                        description: "Fetch single record",
                        displayName: "Self read",
                        group: "User",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 6,
                        name: "user_reset_password",
                        description: null,
                        displayName: "Reset password",
                        group: "User",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 7,
                        name: "user_self_update",
                        description: null,
                        displayName: "Self update",
                        group: "User",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 8,
                        name: "user_self_change_password",
                        description: null,
                        displayName: "Self change password",
                        group: "User",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 9,
                        name: "user_login",
                        description: null,
                        displayName: "User - Login",
                        group: "Public",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 10,
                        name: "role_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Role",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 11,
                        name: "role_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Role",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 12,
                        name: "role_create",
                        description: null,
                        displayName: "Create",
                        group: "Role",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 13,
                        name: "role_update",
                        description: null,
                        displayName: "Update",
                        group: "Role",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 14,
                        name: "permission_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Permission",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 15,
                        name: "permission_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Permission",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 16,
                        name: "subscription_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Subscription",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 17,
                        name: "subscription_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Subscription",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 18,
                        name: "subscription_create",
                        description: null,
                        displayName: "Create",
                        group: "Subscription",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 19,
                        name: "subscription_update",
                        description: null,
                        displayName: "Update",
                        group: "Subscription",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 20,
                        name: "industry_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Industry",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 21,
                        name: "industry_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Industry",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 22,
                        name: "industry_create",
                        description: null,
                        displayName: "Create",
                        group: "Industry",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 23,
                        name: "industry_update",
                        description: null,
                        displayName: "Update",
                        group: "Industry",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 24,
                        name: "skill_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Skill",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 25,
                        name: "skill_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Skill",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 26,
                        name: "skill_create",
                        description: null,
                        displayName: "Create",
                        group: "Skill",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 27,
                        name: "skill_update",
                        description: null,
                        displayName: "Update",
                        group: "Skill",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 28,
                        name: "company_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Company",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 29,
                        name: "company_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Company",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 30,
                        name: "company_create",
                        description: null,
                        displayName: "Create",
                        group: "Company",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 31,
                        name: "company_update",
                        description: null,
                        displayName: "Update",
                        group: "Company",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 32,
                        name: "customer_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Customer",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 33,
                        name: "customer_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Customer",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 34,
                        name: "customer_update",
                        description: null,
                        displayName: "Update",
                        group: "Customer",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 35,
                        name: "customer_reset_password",
                        description: null,
                        displayName: "Reset password",
                        group: "Customer",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 36,
                        name: "customer_subscription_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Customer - Subscription",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 37,
                        name: "customer_subscription_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Customer - Subscription",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 38,
                        name: "customer_subscription_create",
                        description: null,
                        displayName: "Create",
                        group: "Customer - Subscription",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 39,
                        name: "customer_subscription_update",
                        description: null,
                        displayName: "Update",
                        group: "Customer - Subscription",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 40,
                        name: "candidate_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Candidate",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 41,
                        name: "candidate_create",
                        description: null,
                        displayName: "Create",
                        group: "Candidate",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 42,
                        name: "candidate_update",
                        description: null,
                        displayName: "Update",
                        group: "Candidate",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 43,
                        name: "candidate_work_history_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Candidate - Work history",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 44,
                        name: "candidate_work_history_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Candidate - Work history",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 45,
                        name: "candidate_work_history_create",
                        description: null,
                        displayName: "Create",
                        group: "Candidate - Work history",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 46,
                        name: "candidate_work_history_update",
                        description: null,
                        displayName: "Update",
                        group: "Candidate - Work history",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 47,
                        name: "candidate_certification_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Candidate - Certification",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 48,
                        name: "candidate_certification_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Candidate - Certification",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 49,
                        name: "candidate_certification_create",
                        description: null,
                        displayName: "Create",
                        group: "Candidate - Certification",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 50,
                        name: "candidate_certification_update",
                        description: null,
                        displayName: "Update",
                        group: "Candidate - Certification",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 51,
                        name: "candidate_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Candidate - Basic",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 52,
                        name: "candidate_basic_bulk_create",
                        description: null,
                        displayName: "Bulk create",
                        group: "Candidate - Basic",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 53,
                        name: "candidate_basic_upload_profile_image",
                        description: null,
                        displayName: "Upload profile image",
                        group: "Candidate - Basic",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 54,
                        name: "agent_read_all",
                        description: null,
                        displayName: "Read all",
                        group: "Agent",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 55,
                        name: "agent_read",
                        description: "Fetch single record",
                        displayName: "Read",
                        group: "Agent",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 56,
                        name: "agent_create",
                        description: null,
                        displayName: "Create",
                        group: "Agent",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                    {
                        id: 57,
                        name: "agent_update",
                        description: null,
                        displayName: "Update",
                        group: "Agent",
                        isActive: true,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                ],
                { transaction: t }
            )
            //  Assign permissions to role
            const l = 57
            const arrPerms = []
            for (let i = 1; i <= l; i++) {
                arrPerms.push({
                    id: i,
                    roleId: 1,
                    permissionId: i,
                    createdOn: new Date(),
                    modifiedOn: new Date(),
                })
            }
            await query.bulkInsert(
                "role_permission",
                [
                    ...arrPerms,
                    {
                        id: l + 1,
                        roleId: 2,
                        permissionId: 9,
                        createdOn: new Date(),
                        modifiedOn: new Date(),
                    },
                ],
                { transaction: t }
            )
            await query.commitTransaction(t)
        } catch (error) {
            await query.rollbackTransaction(t)
            console.log(error)
        }
    },
    down: async (query: QueryInterface) => {
        const t = await query.sequelize.transaction()
        try {
            await query.startTransaction(t)
            // Remove permissions from role
            await query.bulkDelete(
                "role_permission",
                {
                    id: {
                        [Op.between]: [1, 58],
                    },
                },
                { transaction: t }
            )
            // Delete system permissions in permissin master table
            await query.bulkDelete(
                "permission_master",
                {
                    id: {
                        [Op.between]: [1, 57],
                    },
                },
                { transaction: t }
            )
            await query.commitTransaction(t)
        } catch (error) {
            await query.rollbackTransaction(t)
            console.log(error)
        }
    },
}
